### ISSUE TITLE
occ-cg does not always find uc interactions

### ISSUE THREAD

**Issue by kbal** [peterspackman/occ#8]
I've noticed that occ-cg is not always able to write CrystalGrower input files, failing with an error message such as

` No matching interaction found for uc_mol = 0, dimer = 10`

It seems to occur mostly with chiral molecules. The above error was obtained with Ritonavir form 2, taken directly from the CSD (refcode YIGPIO3). The issue should be quick to reproduce in xTB mode (only running a few s), the precise command being:

`occ-cg YIGPIO03.cif -s toluene --xtb -v debug`

It also seems to be triggered by the particular molecular coordinates in the cif file. As an example, I found S-ibuprofen: refcodes JEKNOC and JEKNOC10 refer to identical unit cells, but with different molecular coordinates (mirrored or shifted). The former is not handled by occ-cg, but the latter is.

I'm not sure wether this is primarily an occ issue or an issue of the cif files. If occ can be made to work by pre-processing the cif input that would also be an acceptable workaround (if documented).

**Comment by peterspackman** [comment]
I'll take a look when I get in next week, thanks for providing the CSD refcodes.

**Comment by peterspackman** [comment]
So the core of the issue was in mapping the interactions for all unit-cell molecules onto the symmetry unique interactions (which are calculated). 

It turned out to be just be a bug in determining how many neighbouring cells to examine for neighbours i.e. an off-by-one error in expanding the unit cells for determining the neighbouring interactions (probably due to the molecule being so large wrt the unit cell). I've added a fix for this in the main branch, I'll close this issue if you can confirm it's working for you now.

Also since you mentioned tight binding, there are some issues with the CG energies when using  tight binding in the main  branch (incorrect total e_int due to not counting both A ->B and B -> A when calculating the solvation component) that I've recently fixed in my development branch (rework_executables) - so please use with caution. In that branch I've also changed the default solvent model when using XTB to cpcmx, and I'm in the process of thoroughly testing things to make sure it's producing consistent results for general use.

**Comment by kbal** [comment]
Thanks for the very quick reply! Tested your solution on some other large molecules and things seem ok, so that's great.

Thanks for the heads-up re:xTB. I'll keep it in mind

**Comment by peterspackman** [comment]
Always happy to help (and fix bugs in the process :grin:) Don't hesitate if there are any more issues
